GameController.class: GameController.java UndoableGame.class
	javac -g GameController.java
IllegalMoveException.class: IllegalMoveException.java
	javac -g IllegalMoveException.java
Move.class: Move.java Token.class
	javac -g Move.java
MoveStack.class: MoveStack.java Token.class
	javac -g MoveStack.java
SimpleGame.class: SimpleGame.java Move.class IllegalMoveException.class
	javac -g SimpleGame.java
Token.class: Token.java
	javac -g Token.java
UndoableGame.class: UndoableGame.java SimpleGame.class MoveStack.class
	javac -g UndoableGame.java

