TYPE=summary
include ../math-FSAB1102.mk

figuresasy: images/figuresasy-1.pdf images/figuresasy-2.pdf images/figuresasy-3.pdf images/figuresasy-4.pdf images/figuresasy-5.pdf images/figuresasy-6.pdf

images/figuresasy-1.pdf: images/figuresasy-1.asy
	cd images/ && asy figuresasy-1.asy

images/figuresasy-2.pdf: images/figuresasy-2.asy
	cd images/ && asy figuresasy-2.asy

images/figuresasy-3.pdf: images/figuresasy-3.asy
	cd images/ && asy figuresasy-3.asy

images/figuresasy-4.pdf: images/figuresasy-4.asy
	cd images/ && asy figuresasy-4.asy

images/figuresasy-5.pdf: images/figuresasy-5.asy
	cd images/ && asy figuresasy-5.asy

images/figuresasy-6.pdf: images/figuresasy-6.asy
	cd images/ && asy figuresasy-6.asy
